export const categories = [
  { value: 0, label: "Усі" },
  { value: 1, label: "Тваринки" },
  { value: 2, label: "Техніка" },
  { value: 3, label: "Природа" },
  { value: 4, label: "Навчання" },
  { value: 5, label: "Музика" },
  { value: 7, label: "Собаки" },
  { value: 8, label: "Софт" },
  { value: 9, label: "Сталкер2" },
  { value: 10, label: "Ігри" },
  { value: 11, label: "#programming" },
  { value: 12, label: "Онлайн ігри" },
  { value: 13, label: "Ігри на linux" },
  { value: 14, label: "#coding" },
  { value: 15, label: "Записи стрімів" },
  { value: 16, label: "Відео проходження" },
  { value: 17, label: "#Меми" },
  { value: 18, label: "#рецепти" },
  { value: 19, label: "#trending" },
  { value: 20, label: "#хендмейд" },
  { value: 21, label: "#techtips" },
  { value: 22, label: "#technews" },
  { value: 23, label: "#tech" },
  { value: 24, label: "#блогер" },
  { value: 25, label: "#Закордон" },
  { value: 26, label: "Github" },
  { value: 28, label: "Stackoverflow" },
  { value: 29, label: "Капібара" },
  { value: 27, label: "#різне" },
  { value: 30, label: "Казна що" },
];
